### PR TITLE
Named text field support, duplicate templates and pandas

### PR DESCRIPTION
**Pull request by eisams**
Hello, I've added support for named text fields

### CODE REVIEW

**Comment by eisams** [comment]
Sorry, new to git. This would also add support for duplicate chart names

**Comment by duarteocarmo** [comment]
Hey @eisams - this looks great. Will review your code changes today and merge. Think these are enough for a new release. Thanks for a great contribution 🥳

**Comment by eisams** [comment]
Happy to help! This should be all the changes

**Comment by duarteocarmo** [comment]
Ok, let me know if you are completely done so I can go and test some of these.

**Comment by eisams** [comment]
Yup, I'm completely done :)

**Comment by duarteocarmo** [comment]
Great, give me some time to test all of this and make sure all ok!

**Comment by duarteocarmo** [comment]
Just a simple change, do you mind running `black -l 79` in both the `thinkcell/thinkcell.py` and the test file? I can also make those changes lmk

**Comment by eisams** [comment]
Done!

**Comment by duarteocarmo** [comment]
Perfect! Merged! Thanks for your contribution!!!

**Comment by duarteocarmo** [comment]
@eisams new release pushed with your added features. thanks again for helping out

**Pull request merged**
